export const enum Permissions {
  SUPER_ADMIN = 'SUPER_ADMIN',

  MODERATE_PRODUCTS_VIEW = 'MODERATE_PRODUCTS_VIEW',
  MODERATE_COMPANIES_VIEW = 'MODERATE_COMPANIES_VIEW',
  MODERATE_PUMPING_VIEW = 'MODERATE_PUMPING_VIEW',
  MODERATE_ACTIVITIES_VIEW = 'MODERATE_ACTIVITIES_VIEW',
  MODERATE_ORDER = 'MODERATE_ORDER',

  USERS_VIEW = 'USERS_VIEW',
  USERS_CREATE = 'USERS_CREATE',
  USERS_EDIT = 'USERS_EDIT',
  USERS_DELETE = 'USERS_DELETE',

  EMPLOYEES_VIEW = 'EMPLOYEES_VIEW',
  EMPLOYEES_CREATE = 'EMPLOYEES_CREATE',
  EMPLOYEES_EDIT = 'EMPLOYEES_EDIT',
  EMPLOYEES_DELETE = 'EMPLOYEES_DELETE',

  FORM_ORDERS_VIEW = 'FORM_ORDERS_VIEW',
  FORM_ORDERS_EDIT = 'FORM_ORDERS_EDIT',

  CATEGORY_FEATURES_VIEW = 'CATEGORY_FEATURES_VIEW',
  CATEGORY_FEATURES_EDIT = 'CATEGORY_FEATURES_EDIT',
  CATEGORY_FEATURES_ADD = 'CATEGORY_FEATURES_ADD',
  CATEGORY_FEATURES_DELETE = 'CATEGORY_FEATURES_DELETE',

  PRODUCT_CATEGORIES_VIEW = 'PRODUCT_CATEGORIES_VIEW',
  PRODUCT_CATEGORIES_ADD = 'PRODUCT_CATEGORIES_ADD',
  PRODUCT_CATEGORIES_EDIT = 'PRODUCT_CATEGORIES_EDIT',
  PRODUCT_CATEGORIES_DELETE = 'PRODUCT_CATEGORIES_DELETE',

  UNITS_VIEW = 'UNITS_VIEW',
  UNITS_ADD = 'UNITS_ADD',
  UNITS_EDIT = 'UNITS_EDIT',
  UNITS_DELETE = 'UNITS_DELETE',

  MAILER_VIEW = 'MAILER_VIEW',
  MAILER_FULL_ACCESS = 'MAILER_FULL_ACCESS',

  MODERATE_RATING_VIEW = 'MODERATE_RATING_VIEW',
  MODERATE_RATING_EDIT = 'MODERATE_RATING_EDIT',
  MODERATE_RATING_DELETE = 'MODERATE_RATING_DELETE',
  MODERATE_RATING_ADD = 'MODERATE_RATING_ADD',
  MODERATE_RATING_STARS = 'MODERATE_RATING_STARS',

  STATISTICS_AND_ANALYTICS_VIEW = 'STATISTICS_AND_ANALYTICS_VIEW',
  STATISTICS_AND_SHOWCASES_VIEW = 'STATISTICS_AND_SHOWCASES_VIEW',

  ROLES_VIEW = 'ROLES_VIEW',
  ROLES_CREATE = 'ROLES_CREATE',
  ROLES_EDIT = 'ROLES_EDIT',
  ROLES_DELETE = 'ROLES_DELETE',

  CHAT_MANAGER_VIEW = 'CHAT_MANAGER_VIEW',
  CHAT_MANAGER_EDIT = 'CHAT_MANAGER_EDIT',
  CHAT_CONSULTANT_VIEW = 'CHAT_CONSULTANT_VIEW',
  CHAT_CONSULTANT_SELLERS = 'CHAT_CONSULTANT_SELLERS',
  CHAT_CONSULTANT_BUYERS = 'CHAT_CONSULTANT_BUYERS',
  CHAT_CONSULTANT_GUESTS = 'CHAT_CONSULTANT_GUESTS',

  BILLING_VIEW = 'BILLING_VIEW',
  BILLING_FULL_ACCESS_FOR_CUSTOMS_AND_DELIVERY = 'BILLING_FULL_ACCESS_FOR_CUSTOMS_AND_DELIVERY',
  BILLING_FULL_ACCESS_FOR_CUSTOMS = 'BILLING_FULL_ACCESS_FOR_CUSTOMS',
  BILLING_FULL_ACCESS_FOR_MANUFACTURERS = 'BILLING_FULL_ACCESS_FOR_MANUFACTURERS',
  BILLING_FULL_ACCESS_FOR_SUPPLIERS = 'BILLING_FULL_ACCESS_FOR_SUPPLIERS',
  BILLING_FULL_ACCESS_FOR_TRADERS = 'BILLING_FULL_ACCESS_FOR_TRADERS',
  BILLING_FULL_ACCESS_FOR_COMPANIES = 'BILLING_FULL_ACCESS_FOR_COMPANIES',

  ORDERS_GROUP = 'ORDERS_GROUP',
  CATEGORY_FEATURES_GROUP = 'CATEGORY_FEATURES_GROUP',
  PRODUCT_CATEGORIES_GROUP = 'PRODUCT_CATEGORIES_GROUP',
  UNITS_GROUP = 'UNITS_GROUP',
  MODERATION_GROUP = 'MODERATION_GROUP',
  CHAT_GROUP = 'CHAT_GROUP',
  USERS_GROUP = 'USERS_GROUP',
  MAILER_GROUP = 'MAILER_GROUP',
  BILLING_GROUP = 'BILLING_GROUP'
}
